In [1]:
import requests
from bs4 import BeautifulSoup
from IPython.core.display import HTML
import pandas as pd
import io

In [2]:
URL = 'https://www.countrymusichalloffame.org/hall-of-fame'

response = requests.get(URL)

In [3]:
response.status_code

200

In [4]:
soup = BeautifulSoup(response.text)

In [5]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <!-- be_ixf, sdk, gho-->
  <meta content="php_sdk_1.5.12" name="be:sdk"/>
  <meta content="98ms" name="be:timer"/>
  <meta content="https%3A%2F%2Fwww.countrymusichalloffame.org%2Fhall-of-fame" name="be:orig_url"/>
  <meta content="https%3A%2F%2Fwww.countrymusichalloffame.org%2Fhall-of-fame" name="be:norm_url"/>
  <meta content="https%3A%2F%2Fixfd1-api.bc0a.com%2Fapi%2Fixf%2F1.0.0%2Fget_capsule%2Ff00000000317463%2F0602379402" name="be:capsule_url"/>
  <meta content="py_2025;pm_09;pd_13;ph_17;pmh_27;p_epoch:1757784435344" name="be:api_dt"/>
  <meta content="py_2025;pm_09;pd_13;ph_17;pmh_27;p_epoch:1757784435344" name="be:mod_dt"/>
  <meta content="Qkdy8Cr6nhjy2N5bPZC0dEHL30YgRwf6EXEqgGZ89MBlmTKB/283KAhoZG7Gyrp6MgZwEcmLupuFJl1Z+3+McBuHwRv2j3cq4chr7385lMr6+foZ9MP9XBpdnfQl6qz96oBs15s7WOeeZP7c56fsbyQD52nPTkwmNjHP6XOkVYLnACuA5woBdNVDCF04Dlc3asnQnvZasWg2BQ5GD9K6ehaRZosHAazOel+0bKwpyl1undDRgrOHNcbVRUqjeUQaOmp+9nE8GJL4FmonQ3lR/fJC+ArXyR8+u9xw8MvNNMqH3one4CYew7BY2oZ0KJLDwxGeHh/XCw74Xkef438sLkL6ivmiq6yCVXNYK7fxyxI7C81bIKUnZbLknjYLiZX2uoh6SiCZlUraRc2HSkQG4rtDGRdS1Fv7HbndWcMrvA3QnyE4TiQxc8uLtLS13JutcF3MgrDhM6KgLr+FOJbr/RRzCGZdkUIhxzhFBwxsFb6NSXV8hHlzQEbbIrCFyOVIaObaCqrdfIGfhmBWiZ2wCQ/7AhWyseBJvrFcLpv7cLEB8Xl6SKvqbHG1fmM7MKS9VyqOgmkvfQr9lbJFtsbYMucIwEH94Gu8MwoS01PsCOz6uke3LdxctqhmXuSEBmfgaRtqRVOjpgDRHfOk8bwIhoX9t1OcVpugP3BUl7ciYl4weG596mFQWMcxHqYtK+w80V8S09jOVH30vRSM/WyGdoy0HFl46uM4s7CES7s53/+Dk+1GkJeT1DxymEbIbbLp5hzPZHl7GYsBPq0EiNb25nHEUhrabeBzs1cvgaUwIzyKdoWm4gz1UQKtWrkdzrV+dx6SPCSRJbxfCAVDoJgFw7Wqi4YdbK+Nwmulea7hZ2LM875UeTliEPsfO5UiRJwoypP+Vtr9dfN7n+ua022zDW/8XaHtCceUGvb1rv/38tV1WgaD1rJhfIdpESZzgKYsmSQpSRoeFxxi0ggG1kQtXJ6dPvg7KO4IY+Fo5gCAWc2iS8QKCzBN+uFTcDbbtI68rLyrg/yT58CDSDmQ0TMSTiE3edVgBOpe0wMQgGBLpBzCtPEq3xsJ4BvbNlQ5OTzBjNovWlGZhVrgDo9A6GqO2GRp46A2VzIVBmTNqSW6ePnO85R826vA7qERjzxy5IveQ4w6rxtiUapTxDIXN6NH8a74kNagNVAzyop+h4StWrBJUlkE7AACXHYCk3O6SehxgiaGU9eEF3J06k8PTmnlYIu6R8OmjKKSQjzYKDK08TEUE8VnWtN+E/3iv3p/AQusUi+RZwf7ZmYFO4W8s8E5e+NxQ3udjA9IbloOrPlsbF52F6FeCiwxxvHt/GfBBJuQbX8/DOa5M19j743ICDmzdzlQNzMdsVhbIrHrL1znTkP1xlZBK3Z/SRSBtDUOOBb3684Z76JzUbyfJt0QvG/HezCx9v/B+hWoV2HvFMwyaKLyQlKHJGneHL5MI/e3grotAMFv5Mg022uuvmVnEQ0ATwkdJ58AMDk3vB+nGYD8ft9OhV6vkf6riahXhVtEw0AnlrAbORQJaVLolm4l2iuzTdTXq4+GtSghL8lKvKWWNo2+qTkYX9UIXWETLrcQw9OUYr26KooGEyvRRYsu3S6qPpbBpPZvnvf2eb+cAXgQae5ZFIEvdXlDTH0wplQPaSaBu/KbOH4RqGybI70Uvc2ABqSzq3TpjYke0DczMHowy4Euuye0S5Ww5z5a0ib1Wlp6GHnjJ3z2Jx75Ba9ZVOMfbLQ+RCRDoj4/pTLF3ttvQbdaeD1H/s1r7JVh4GuokCaH7OU+Eb8eH+ciA+uu54Rh/3MC4zt2w/YGDGyfNv6LVN4K3c5d8txyij3C/Z/R16w0GFTOf5QRiNvdQjMqvlbbwCAW/cby+gb/ggKnFhJXa66nkr9CK9leWIwfN7Ct7SGrCndaNNmG8Fj7RpRidCGtKSevQwWvWDIWDAQAHbo0w5hupJS1yp2Y3KYHl04zbVAm867EgsjTV+V48BAuyfqJve6g6LLn9F9kFtKFkFjsRpa4jOSzjcmu8H7xxBRgw4bTN/Jb0quNu0DrvOBzmkkCkTsv+WFCWNyU+TeraAZKks1QFGe7eFFz+ED2S2qY0RIx1YtudYw98w4Zx+gjxMVKFcgPdX/NmTgWf0mAEdOuZRVASAzaInL0JDDdXB+x+EDokYwYW6OfW0rNYt8nNXaLmOOAV5xJ7lGwEBNv+pagVW2HTgup6f3Ufp5R7Oi6L4XcBKLmHDjr5m32qHOzHqhJf8dZT6+v+q3VK3ZIH2p4n5ZUZeTdvWI5hqjA6yDyNCxWcjLP2IWQaG18IZDkf0pFGEdvDl0K7Zjw8OhIaZKRb8Y=" name="be:diag"/>
  <meta content="false" name="be:messages"/>
  <style>
   .be-ix-link-block {background-color: #141414;}
.be-ix-link-block .be-related-link-container {padding-bottom: 20px;}
.be-ix-link-block .be-related-link-container .be-label {margin: 0;color: white;line-height: 1em;font-variant-numeric: lining-nums; font-family: trade-gothic-next-condensed, Helvetica, Arial, "Arial Unicode", "Lucida Sans Unicode", sans-serif;}
.be-ix-link-block .be-related-link-container .be-list { display: inline-block; list-style: none;margin: 0; padding: 0;}
.be-ix-link-block .be-related-link-container .be-list .be-list-item {display: inline-block;margin-right: 20px;margin-bottom: 6px;}
.be-ix-link-block .be-related-link-container .be-list .be-list-item .be-related-link {font-family: trade-gothic-next-condensed, Helvetica, Arial, "Arial Unicode", "Lucida Sans Unicode", sans-serif;
    font-size: 1.25rem;
    line-height: 1;
    letter-spacing: 0.06em;
    text-decoration: none;
    font-weight: 800;
    font-style: normal;
    color: #fff;}
.be-ix-link-block .be-related-link-container .be-list .be-list-item .be-related-link:hover {text-decoration: underline;color: #F0B23A;color: #F0B23A;}
.be-ix-link-block .be-related-link-container .be-list .be-list-item:last-child { margin-right: 0;}

@media (max-width: 767px) {
  .be-ix-link-block .be-related-link-container .be-label {width: 100%;margin-bottom: 10px;}
  .be-ix-link-block .be-related-link-container .be-list { display: block;width: 100%;}
  .be-ix-link-block .be-related-link-container .be-list .be-list-item {display: block;margin-right: 0;}
}
@media (min-width: 768px) {
  .be-ix-link-block .be-related-link-container {display: flex;align-items: baseline;}
  .be-ix-link-block .be-related-link-container .be-label {display: inline-block;margin-right: 20px;flex-grow: 0;flex-shrink: 0;}
}
  </style>
  <script data-customerid="f00000000317463" data-delay="0" data-testmode="false" id="be-app-script" src="https://app-cf.bc0a.com/corejs/be-app.js">
  </script>
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-TVMMMDC');
  </script>
  <!-- End Google Tag Manager -->
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-TWK5NBL');
  </script>
  <!-- End Google Tag Manager -->
  <!-- Google Tag Manager -->
  <script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-TP83XWPT');
  </script>
  <!-- End Google Tag Manager -->
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href="/dist/css/motif.d9dacbadf92b95c78f7763750a0e9775.css" rel="stylesheet"/>
  <script>
   window.Motif = {
    core: {},
    pages: {},
    shared: {},
    utils: {},
    apps: {}
  };

  window.CMHOF = {
    exteriorDomainExclusions: ["hatchshowprint.com","studiob.org","cmatheater.com","cmhof.imgix.net","cmhof.typeform.com","nashvillemta.org","cdc.org","paylocity.com","twitter.com","youtube.com","instagram.com","facebook.com","issuu.com","open.spotify.com"] // exterior domain exclusions
  };
  </script>
  <!-- Important Scripts -->
  <script src="/dist/js/helpers.motif.d2920f2102a30047f0f309f900fc3f81.js" type="text/javascript">
  </script>
  <!-- End Important Scripts -->
  <meta content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" name="robots"/>
  <meta content="en_US" property="og:locale"/>
  <meta content="article" property="og:type"/>
  <meta content="Hall of Fame - Country Music Hall of Fame and Museum" property="og:title"/>
  <meta content="https://www.countrymusichalloffame.org/hall-of-fame" property="og:url"/>
  <meta content="Country Music Hall of Fame and Museum" property="og:site_name"/>
  <meta content="2022-06-20T14:20:25+00:00" property="article:modified_time"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" name="robots"/>
  <title>
   Hall of Fame - Country Music Hall of Fame and Museum
  </title>
  <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <script>
   (function(h,o,t,j,a,r){
                h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                h._hjSettings={hjid:1263612,hjsv:5};
                a=o.getElementsByTagName('head')[0];
                r=o.createElement('script');r.async=1;
                r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                a.appendChild(r);
            })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
  </script>
 </head>
 <body class="">
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-TVMMMDC" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-TWK5NBL" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <!-- Google Tag Manager (noscript) -->
  <noscript>
   <iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-TP83XWPT" style="display:none;visibility:hidden" width="0">
   </iframe>
  </noscript>
  <!-- End Google Tag Manager (noscript) -->
  <div aria-describedby="gdpr-accept" aria-modal="true" class="gdpr color--white" id="gdpr">
   <div class="gdpr__content background--caption-black zi--10">
    <div class="wrappers__wrapper presentational__relative-container">
     <div class="gdpr__flex flex flex__jc--center flex__ai--flex-start flex__stack--sm">
      <div class="gdpr__icon">
       <svg class="icons__icon color--brand-primary">
        <use xlink:href="#cookies">
        </use>
       </svg>
      </div>
      <div class="flex flex__ai--flex-start flex__stack--med">
       <p class="gdpr__copy hierarchy__minion-text" id="gdpr-description">
        We use cookies in the following ways: (1) for system administration, (2) to assess the performance of the website, (3) to personalize your experience, content and ads, (4) to provide social media features, and (5) to analyze our traffic. You consent to our cookies if you continue to use our website.  Please consult instructions for your web browser to disable or block cookies, or to receive a warning before a cookie is stored on your computer or mobile device. Read our
        <a class="links__inline" data-focus="first" href="/plan-your-visit/museum-policies-faq/privacy-policy/">
         Privacy Policy
        </a>
        .
       </p>
       <button class="gdpr__accept button__primary" id="gdpr-accept" type="button">
        That's Fine
       </button>
      </div>
     </div>
     <button class="gdpr__close button__no-button" data-focus="last" id="gdpr-close" type="button">
      <svg class="icons__icon">
       <use xlink:href="#close">
       </use>
      </svg>
      <span class="presentational__is-hidden">
       Close GDPR alert
      </span>
     </button>
    </div>
   </div>
  </div>
  <header class="globalHeader">
   <div class="navigation background--charcoal js-navigation">
    <div class="navigation--sm background--charcoal color--white">
     <div class="wrappers__wrapper">
      <div class="flex flex__jc--space-between">
       <div class="navigation__branding--sm">
        <figure class="navigation__branding-figure presentational__relative-container spacing__mtn">
         <a aria-label="Country Music Hall of Fame - Home" class="links__overlay" href="/" rel="home">
         </a>
         <img alt="Country Music Hall of Fame logo." src="https://cmhof.imgix.net/resources/cmhof-logo.svg" width="80px"/>
        </figure>
       </div>
       <div class="navigation__controls flex flex__jc--space-between flex__ai--center">
        <a class="links__ticket links__ticket--sm" href="/select-your-experience">
         Museum
        </a>
        <a class="navigation__controls-cart links__unlink spacing__mll" href="#" target="_blank">
         <svg class="icons__icon color--white">
          <use xlink:href="#cart">
          </use>
         </svg>
         <span class="presentational__is-hidden">
          View Cart
         </span>
        </a>
        <button class="button__no-button spacing__mll js-navigation-reveal">
         <div class="navigation__controls-open">
          <svg class="icons__icon">
           <use xlink:href="#menu">
           </use>
          </svg>
          <span class="presentational__is-hidden">
           Open navigation
          </span>
         </div>
         <div class="navigation__controls-close">
          <svg class="icons__icon">
           <use xlink:href="#close">
           </use>
          </svg>
          <span class="presentational__is-hidden">
           Close navigation
          </span>
         </div>
        </button>
       </div>
      </div>
     </div>
    </div>
    <div class="wrappers__wrapper" id="navigation-main">
     <div class="navigation__branding wrappers__offset--left zi--100">
      <figure class="navigation__branding-figure presentational__relative-container spacing__mtn">
       <a aria-label="Country Music Hall of Fame - Home" class="links__overlay" href="/" rel="home">
       </a>
       <img alt="Country Music Hall of Fame logo." src="https://cmhof.imgix.net/resources/cmhof-logo.svg" width="140px"/>
      </figure>
     </div>
     <div class="navigation--sm-flex js-navigation-sm">
      <nav aria-label="Eyebrow" class="navigation__eyebrow flex flex__jc--space-between flex__stack--med-reverse">
       <form action="/search" class="navigation__search presentational__relative-container js-gauntlet" method="GET" role="search">
        <div aria-hidden="true" class="navigation__search-submit">
         <svg class="icons__icon color--white">
          <use xlink:href="#search">
          </use>
         </svg>
        </div>
        <label class="presentational__relative-container presentational__new-line">
         <span class="presentational__is-hidden" id="search-instructions">
          Type in your search keywords and press Enter to submit
         </span>
         <input aria-describedby="search-instructions" autocomplete="off" class="navigation__search-field styles__body-text js-input-filled" name="s" type="search"/>
         <span aria-hidden="true" class="navigation__search-label styles__secondary--compressed color--brand-primary">
          Search
         </span>
        </label>
       </form>
       <ul class="lists__unstyled navigation__eyebrow-list">
        <li class="navigation__eyebrow-item" data-name="collections">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/about/collections">
          Collections
         </a>
        </li>
        <li class="navigation__eyebrow-item" data-name="exhibitions">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/experiences/calendar/exhibitions">
          Exhibitions
         </a>
        </li>
        <li class="navigation__eyebrow-item" data-name="about">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/about">
          About
         </a>
        </li>
        <li class="navigation__eyebrow-item" data-name="donate">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/support/donate">
          Donate
         </a>
        </li>
        <li class="navigation__eyebrow-item" data-name="membership">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/support/membership">
          Membership
         </a>
        </li>
        <li class="navigation__eyebrow-item" data-name="venue-rental">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/plan-your-visit/venue-rental">
          Venue Rental
         </a>
        </li>
        <li class="navigation__eyebrow-item" data-name="account">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/account">
          <svg class="icons__icon color--white spacing__mrm">
           <use xlink:href="#account">
           </use>
          </svg>
          Account
         </a>
        </li>
        <li class="navigation__eyebrow-item" data-name="cart">
         <a class="navigation__eyebrow-item--link styles__secondary--compressed" href="/cart">
          <svg class="icons__icon color--white">
           <use xlink:href="#cart">
           </use>
          </svg>
          <span class="presentational__is-hidden">
           Cart
          </span>
         </a>
        </li>
        <li class="navigation__eyebrow-item navigation__eyebrow-item--cta">
         <a class="links__ticket links__ticket--sm" href="/select-your-experience">
          Museum Tickets
         </a>
        </li>
       </ul>
      </nav>
      <nav aria-label="Primary" class="navigation__primary">
       <ul class="navigation__primary-list lists__unstyled">
        <li class="navigation__primary-item js-primary-nav">
         <button class="navigation__primary-item--link navigation__primary-item-reveal button__no-button styles__secondary--condensed links__nav js-nav-small" data-caret="slate" data-reveal="main-hall-of-fame-members" data-reveal-group="navigation" id="reveal-main-hall-of-fame-members">
          Hall of Fame
         </button>
         <div class="navigation__secondary zi--10 background--slate-light" id="main-hall-of-fame-members">
          <div class="navigation__secondary-grid wrappers__lg-up" data-grid="three">
           <nav class="navigation__secondary-nav">
            <div class="dropdownLinks">
             <button class="dropdownLinks__back button__no-button links__link links__link--tiny links__link--dark" data-reveal-for="reveal-main-hall-of-fame-members" type="button">
              <svg class="icons__icon color--brand-primary">
               <use xlink:href="#nav-left">
               </use>
              </svg>
              Back
             </button>
             <ul class="dropdownLinks__primary flex flex__dir--column flex__wrp--wrap lists__unstyled spacing__mtn">
              <li class="dropdownLinks__primary-item has-children">
               <a class="dropdownLinks__primary-link links__link links__link--brand" href="/hall-of-fame">
                Hall of Fame
               </a>
               <ul class="dropdownLinks__children lists__unstyled">
                <li class="dropdownLinks__children-item hierarchy__normal-text spacing__mtn">
                 <a class="dropdownLinks__children-link styles__secondary--condensed color--white" href="/hall-of-fame">
                  All Members
                 </a>
                </li>
                <li class="dropdownLinks__children-item hierarchy__normal-text">
                 <a class="dropdownLinks__children-link styles__secondary--condensed color--white" href="/hall-of-fame/current-class">
                  Current Hall of Fame Class
                 </a>
                </li>
                <li class="dropdownLinks__children-item hierarchy__normal-text">
                 <a class="dropdownLinks__children-link styles__secondary--condensed color--white" href="/hall-of-fame/election-process">
                  Election Process
                 </a>
                </li>
                <li class="dropdownLinks__children-item hierarchy__normal-text">
                 <a class="dropdownLinks__children-link styles__secondary--condensed color--white" href="/hall-of-fame/induction-ceremony">
                  Induction: Medallion Ceremony
                 </a>
                </li>
                <li class="dropdownLinks__children-item hierarchy__normal-text">
                 <a class="dropdownLinks__children-link styles__secondary--condensed color--white" href="/hall-of-fame/circle-guard">

#### 1.	Start by using either the inspector or by viewing the page source. Can you identify a tag that might be helpful for finding the names of all inductees? Make use of this to create a list containing just the names of each inductee.

In [7]:
soup.find('h2').text

'\n                    Roy Acuff                '

In [8]:
inductee_names = [name.text.strip() for name in soup.find_all('h2')]

print(f"Amount of inductee names: {len(inductee_names)}")

Amount of inductee names: 310

In [9]:
print(inductee_names[:5])

['Roy Acuff', 'Alabama', 'Bill Anderson', 'John Anderson', 'Eddy Arnold']

#### 2.	Next, try and find a tag that could be used to find the year that each member was inducted. Extract these into a list. When you do this, be sure to only include the year and not the full text. For example, for Roy Acuff, the list entry should be "1962" and not "Inducted 1962". Double-check that the resulting list has the correct number of elements and is in the same order as your inductees list.

In [11]:
soup.find('h3').text

'\n                    Inducted 1962                                    '

In [12]:
inductee_year = [year.text.strip().split()[-1] for year in soup.find_all('h3')]

print(f"Amount of induxtee years: {len(inductee_year)}")

Amount of induxtee years: 310

In [13]:
print(inductee_year[:5])

['1962', '2005', '2001', '2024', '1966']

#### 3.	Take the two lists you created on parts 1 and 2 and convert it into a pandas DataFrame.

In [15]:
df = pd.DataFrame({
    "Name": inductee_names,
    "Year": inductee_year
})

print(df)

               Name  Year
0         Roy Acuff  1962
1           Alabama  2005
2     Bill Anderson  2001
3     John Anderson  2024
4       Eddy Arnold  1966
..              ...   ...
305      Bob McDill  2023
306  Patty Loveless  2023
307    James Burton  2024
308   John Anderson  2024
309      Toby Keith  2024

[310 rows x 2 columns]

#### 4.	If you navigate to Roy Acuff's page, you will see that his date of birth and date of death are listed towards the top of the page, along with his birthplace. Write some code that will extract these three values. Once you get it working for Roy Acuff, figure out how you can extract these values across the whole dataset of artists. In doing this, you'll need to figure out a way to automatically determine the correct urls for each artist. Note also that not every artist will have these three values, so write your code in a way that it can handle cases where these values are missing. Alabama is one such example.

In [17]:
person_urls = ["https://www.countrymusichalloffame.org/hall-of-fame/" + name.replace(" ", "-") for name in inductee_names]

print(person_urls[:5])

['https://www.countrymusichalloffame.org/hall-of-fame/Roy-Acuff', 'https://www.countrymusichalloffame.org/hall-of-fame/Alabama', 'https://www.countrymusichalloffame.org/hall-of-fame/Bill-Anderson', 'https://www.countrymusichalloffame.org/hall-of-fame/John-Anderson', 'https://www.countrymusichalloffame.org/hall-of-fame/Eddy-Arnold']

In [18]:
df['person_url'] = person_urls

df.head(5)

            Name  Year                                         person_url
0      Roy Acuff  1962  https://www.countrymusichalloffame.org/hall-of...
1        Alabama  2005  https://www.countrymusichalloffame.org/hall-of...
2  Bill Anderson  2001  https://www.countrymusichalloffame.org/hall-of...
3  John Anderson  2024  https://www.countrymusichalloffame.org/hall-of...
4    Eddy Arnold  1966  https://www.countrymusichalloffame.org/hall-of...

In [19]:
def get_date_of_birth(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text)

        date_of_birth_block = soup.find("span", class_="headerPerson__details-item--term", string=lambda s: s and "Born" in s)
        
        date_of_birth = (date_of_birth_block.find_next("div", class_="headerPerson__details-item--def").text.strip())
        
        return date_of_birth
    except:
        # print(f"Error for {url}")
        return "unknown"

In [20]:
def get_date_of_death(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text)

        date_of_death_block = soup.find("span", class_="headerPerson__details-item--term", string=lambda s: s and "Died" in s)
        
        date_of_death = (date_of_death_block.find_next("div", class_="headerPerson__details-item--def").text.strip())
        
        return date_of_death
    except:
        # print(f"Error for {url}")
        return "unknown"

In [21]:
def get_birthplace(url):
    try:
        response = requests.get(url)
        soup = BeautifulSoup(response.text)

        birthplace_block = soup.find("span", class_="headerPerson__details-item--term", string=lambda s: s and "Birthplace" in s)
        
        birthplace = (birthplace_block.find_next("div", class_="headerPerson__details-item--def").text.strip())
        
        return birthplace
    except:
        # print(f"Error for {url}")
        return "unknown"

In [22]:
df['date_of_birth'] = df['person_url'].apply(get_date_of_birth)
df['date_of_death'] = df['person_url'].apply(get_date_of_death)
df['birthplace'] = df['person_url'].apply(get_birthplace)

df.head()

,Name,Year,person_url,date_of_birth,date_of_death,birthplace
0,Roy Acuff,1962,https://www.countrymusichalloffame.org/hall-of...,"September 15, 1903","November 23, 1992","Maynardville, Tennessee"
1,Alabama,2005,https://www.countrymusichalloffame.org/hall-of...,unknown,unknown,unknown
2,Bill Anderson,2001,https://www.countrymusichalloffame.org/hall-of...,"November 1, 1937",unknown,"Columbia, South Carolina"
3,John Anderson,2024,https://www.countrymusichalloffame.org/hall-of...,"December 13, 1954",unknown,"Orlando, Florida"
4,Eddy Arnold,1966,https://www.countrymusichalloffame.org/hall-of...,"May 15, 1918","May 8, 2008","Henderson, Tennessee"